<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTask(Category $category){
            $this->createQueryBuilder('t')
                ->select('t')
                ->andWhere('t.category = :category')
                ->setParameter(':id', $category->getId())
                ->getQuery()
                ->getResult();
        }

}
