# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password:  $2y$12$TxEQjz2nsvdQkXRRyjyJSeCgk8e.yMS/ibackA1u89B1yAvdgTjGq
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$YIkxHqRPNzWdzi6aiD1PZO73YxuEiBzmWxR/D6Fxk/4cbIaR8LNlu
                        roles: 'ROLE_ADMIN'

    encoders:
            Symfony\Component\Security\Core\User\User:
                algorithm: bcrypt
                cost: 12


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~



    access_control:
            - { path: ^/, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
