# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.category.manager:
        class: AppBundle\Manager\CategoryManager
        arguments: ["@=service('doctrine').getManager()"]

    app.task.manager:
            class: AppBundle\Manager\TaskManager
            arguments: ["@=service('doctrine').getManager()"]
