# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.category.manager:
        class: AppBundle\Manager\CategoryManager
        arguments: ["@=service('doctrine').getManager()"]

    app.task.manager:
            class: AppBundle\Manager\TaskManager
            arguments: ["@=service('doctrine').getManager()"]

    app.normalizer.category:
            class: AppBundle\Serializer\Normalizer\CategoryNormalizer
            tags:
                - { name: serializer.normalizer }

    app.normalizer.task:
                class: AppBundle\Serializer\Normalizer\TaskNormalizer
                tags:
                    - { name: serializer.normalizer }

    admin.category:
            class: AppBundle\Admin\CategoryAdmin
            arguments: [~, AppBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Category }

    admin.task:
            class: AppBundle\Admin\TaskAdmin
            arguments: [~, AppBundle\Entity\Task, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Task }